chainid: "168587773"
network: blast-sepolia
factories1155:
  - address: "0x777777C338d93e2C7adf08D102d45CA7CC4Ed021"
    startBlock: "2273642"
    version: "1"
factories721:
  - address: ""
    startBlock: ""
    version: "1"
protocolRewards:
  - address: "0x7777777F279eba3d3Ad8F4E708545291A6fDBA8B"
    startBlock: "2272323"
    version: "1"
