name: "Cache foundry build"
description: "Caches foundry build by path"

inputs:
  package_folder: # id of input
    description: "contracts package folder"
    required: true
  foundry_profile:
    description: "foundry profile for caching"

runs:
  using: "composite"

  steps:
    - name: Cache contracts build
      uses: actions/cache@v4
      env:
        base_cache_key: ${{ inputs.package_folder }}${{ inputs.foundry_profile}}
        src_cache_key: ${{ hashFiles(format('{0}/src/**/*.sol', inputs.package_folder)) }}
        test_cache_key: ${{ hashFiles(format('{0}/test/**/*.sol', inputs.package_folder)) }}
        scripts_cache_key: ${{ hashFiles(format('{0}/script/**/*.sol', inputs.package_folder)) }}
        foundry_config_cache_key: ${{ hashFiles(format('{0}/foundry.toml', inputs.package_folder)) }}
        package_json_cache_key: ${{ hashFiles(format('{0}/package.json', inputs.package_folder)) }}
      with:
        # npm cache files are stored in out and cache
        path: |
          ${{ inputs.package_folder }}/cache
          ${{ inputs.package_folder }}/out
        # cache key is based on: base_cache_key + src_cache_key + test_cache_key + scripts_cache_key + foundry_config_cache_key + package_json_cache_key:
        key: ${{ env.base_cache_key }}-${{ env.src_cache_key }}-${{ env.test_cache_key }}-${{ env.scripts_cache_key }}-${{ env.foundry_config_cache_key }}-${{ env.package_json_cache_key }}
        # the following backups cache keys are searched, in case an exact match is not found
        # see https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#matching-a-cache-key
        restore-keys: |
          ${{ env.base_cache_key }}-${{ env.src_cache_key }}-${{ env.test_cache_key }}-${{ env.scripts_cache_key }}-${{ env.foundry_config_cache_key }}-${{ env.package_json_cache_key }}
          ${{ env.base_cache_key }}-${{ env.src_cache_key }}-${{ env.test_cache_key }}-${{ env.scripts_cache_key }}-${{ env.foundry_config_cache_key }}-
          ${{ env.base_cache_key }}-${{ env.src_cache_key }}-${{ env.test_cache_key }}-${{ env.scripts_cache_key }}-
          ${{ env.base_cache_key }}-${{ env.src_cache_key }}-${{ env.test_cache_key }}-
          ${{ env.base_cache_key }}-${{ env.src_cache_key }}-
          ${{ env.base_cache_key }}-
